const BASE_API_URL =(typeof import.meta !== 'undefined' && (import.meta as { env?: { VITE_API_URL?: string } }).env?.VITE_API_URL) ||
  (typeof process !== 'undefined' && (process as { env?: { VITE_API_URL?: string } }).env?.VITE_API_URL) ||
  'http://localhost:5000';

function url(path: string): string {
  const p = path.startsWith('/') ? path : `/${path}`;
  return `${BASE_API_URL.replace(/\/$/, '')}${p}`;
}

export const config = {
  baseApiUrl: BASE_API_URL,
  api: {
    auth: {
      me: url('/api/auth/me'),
      login: url('/api/auth/login'),
      logout: url('/api/auth/logout'),
      refresh: url('/api/auth/refresh'),
      forgotPassword: url('/api/auth/forgot-password'),
      resetPassword: url('/api/auth/reset-password'),
      verifyOtp: url('/api/auth/verify-otp'),
      resendOtp: url('/api/auth/resend-otp'),
    },
    upload: {
      single: url('/api/upload/single'),
      multiple: url('/api/upload/multiple'),
      presignedUrl: (key: string) => url(`/api/upload/files/${encodeURIComponent(key)}/presigned-url`),
      deleteFile: (key: string) => url(`/api/upload/files/${encodeURIComponent(key)}`),
    },
    regions: {
      list: url('/api/regions'),
      create: url('/api/regions'),
      byId: (id: string) => url(`/api/regions/${id}`),
      update: (id: string) => url(`/api/regions/${id}`),
      delete: (id: string) => url(`/api/regions/${id}`),
      packages: (id: string) => url(`/api/regions/${id}/packages`),
      assignPackage: (id: string) => url(`/api/regions/${id}/packages`),
      removePackage: (id: string, packageId: string) => url(`/api/regions/${id}/packages/${packageId}`),
      yachts: (id: string) => url(`/api/regions/${id}/yachts`),
      assignYacht: (id: string) => url(`/api/regions/${id}/yachts`),
    },
    charterCompanies: {
      list: url('/api/charter-companies'),
      create: url('/api/charter-companies'),
      byId: (id: string) => url(`/api/charter-companies/${id}`),
      update: (id: string) => url(`/api/charter-companies/${id}`),
      delete: (id: string) => url(`/api/charter-companies/${id}`),
    },
    yachts: {
      list: url('/api/yachts'),
      create: url('/api/yachts'),
      byId: (id: string) => url(`/api/yachts/${id}`),
      detail: (id: string) => url(`/api/yachts/${id}/detail`),
      update: (id: string) => url(`/api/yachts/${id}`),
      delete: (id: string) => url(`/api/yachts/${id}`),
      status: (id: string) => url(`/api/yachts/${id}/status`),
      images: (id: string) => url(`/api/yachts/${id}/images`),
      uploadImages: (id: string) => url(`/api/yachts/${id}/images`),
      image: (yachtId: string, imageId: string) => url(`/api/yachts/${yachtId}/images/${imageId}`),
      amenities: (id: string) => url(`/api/yachts/${id}/amenities`),
      addAmenity: (id: string) => url(`/api/yachts/${id}/amenities`),
      amenity: (yachtId: string, amenityId: string) => url(`/api/yachts/${yachtId}/amenities/${amenityId}`),
      documents: (id: string) => url(`/api/yachts/${id}/documents`),
      uploadDocument: (id: string) => url(`/api/yachts/${id}/documents`),
      document: (yachtId: string, docId: string) => url(`/api/yachts/${yachtId}/documents/${docId}`),
      maintenance: (id: string) => url(`/api/yachts/${id}/maintenance`),
      addMaintenance: (id: string) => url(`/api/yachts/${id}/maintenance`),
      maintenanceItem: (yachtId: string, mId: string) => url(`/api/yachts/${yachtId}/maintenance/${mId}`),
      availabilityCheck: (id: string) => url(`/api/yachts/${id}/availability/check`),
      availabilityBlock: (id: string) => url(`/api/yachts/${id}/availability/block`),
      availability: (id: string) => url(`/api/yachts/${id}/availability`),
      removeBlock: (id: string, blockId: string) => url(`/api/yachts/${id}/availability/${blockId}`),
    },
    blog: {
      list: url('/api/blog'),
      byId: (id: string) => url(`/api/blog/${id}`),
      create: url('/api/blog'),
      update: (id: string) => url(`/api/blog/${id}`),
      delete: (id: string) => url(`/api/blog/${id}`),
      updateStatus: (id: string) => url(`/api/blog/${id}/status`),
    },
    tags: {
      list: url('/api/tags'),
      byId: (id: string) => url(`/api/tags/${id}`),
      create: url('/api/tags'),
      update: (id: string) => url(`/api/tags/${id}`),
      delete: (id: string) => url(`/api/tags/${id}`),
    },
    packages: {
      list: url('/api/packages'),
      create: url('/api/packages'),
      byId: (id: string) => url(`/api/packages/${id}`),
      update: (id: string) => url(`/api/packages/${id}`),
      delete: (id: string) => url(`/api/packages/${id}`),
      status: (id: string) => url(`/api/packages/${id}/status`),
      regions: (id: string) => url(`/api/packages/${id}/regions`),
      updateRegions: (id: string) => url(`/api/packages/${id}/regions`),
      services: (id: string) => url(`/api/packages/${id}/services`),
      addService: (id: string) => url(`/api/packages/${id}/services`),
      service: (packageId: string, sId: string) => url(`/api/packages/${packageId}/services/${sId}`),
      addons: (id: string) => url(`/api/packages/${id}/addons`),
      createAddon: (id: string) => url(`/api/packages/${id}/addons`),
      addon: (packageId: string, addonId: string) => url(`/api/packages/${packageId}/addons/${addonId}`),
      media: (id: string) => url(`/api/packages/${id}/media`),
      uploadMedia: (id: string) => url(`/api/packages/${id}/media`),
      mediaItem: (packageId: string, mediaId: string) => url(`/api/packages/${packageId}/media/${mediaId}`),
    },
    bookings: {
      list: url('/api/bookings'),
      create: url('/api/bookings'),
      calendar: url('/api/bookings/calendar'),
      availability: url('/api/bookings/availability'),
      byId: (id: string) => url(`/api/bookings/${id}`),
      update: (id: string) => url(`/api/bookings/${id}`),
      cancel: (id: string) => url(`/api/bookings/${id}`),
      status: (id: string) => url(`/api/bookings/${id}/status`),
      confirm: (id: string) => url(`/api/bookings/${id}/confirm`),
      cancelPost: (id: string) => url(`/api/bookings/${id}/cancel`),
      complete: (id: string) => url(`/api/bookings/${id}/complete`),
      invoice: (id: string) => url(`/api/bookings/${id}/invoice`),
      sendConfirmation: (id: string) => url(`/api/bookings/${id}/send-confirmation`),
      sendReminder: (id: string) => url(`/api/bookings/${id}/send-reminder`),
      addons: (id: string) => url(`/api/bookings/${id}/addons`),
      addAddon: (id: string) => url(`/api/bookings/${id}/addons`),
      removeAddon: (id: string, addonId: string) => url(`/api/bookings/${id}/addons/${addonId}`),
      payments: (id: string) => url(`/api/bookings/${id}/payments`),
      recordPayment: (id: string) => url(`/api/bookings/${id}/payments`),
      payment: (bookingId: string, paymentId: string) => url(`/api/bookings/${bookingId}/payments/${paymentId}`),
      refund: (bookingId: string, paymentId: string) => url(`/api/bookings/${bookingId}/payments/${paymentId}/refund`),
    },
    pricing: {
      rules: {
        list: url('/api/pricing/rules'),
        create: url('/api/pricing/rules'),
        byId: (id: string) => url(`/api/pricing/rules/${id}`),
        update: (id: string) => url(`/api/pricing/rules/${id}`),
        status: (id: string) => url(`/api/pricing/rules/${id}/status`),
        delete: (id: string) => url(`/api/pricing/rules/${id}`),
      },
      promoCodes: {
        validate: url('/api/pricing/promo-codes/validate'),
        list: url('/api/pricing/promo-codes'),
        create: url('/api/pricing/promo-codes'),
        byId: (id: string) => url(`/api/pricing/promo-codes/${id}`),
        update: (id: string) => url(`/api/pricing/promo-codes/${id}`),
        delete: (id: string) => url(`/api/pricing/promo-codes/${id}`),
      },
      currencies: {
        list: url('/api/pricing/currencies'),
        create: url('/api/pricing/currencies'),
        refreshRates: url('/api/pricing/currencies/refresh-rates'),
        byCode: (code: string) => url(`/api/pricing/currencies/${encodeURIComponent(code)}`),
        update: (code: string) => url(`/api/pricing/currencies/${encodeURIComponent(code)}`),
        delete: (code: string) => url(`/api/pricing/currencies/${encodeURIComponent(code)}`),
      },
      agents: {
        list: url('/api/pricing/agents'),
        create: url('/api/pricing/agents'),
        byId: (id: string) => url(`/api/pricing/agents/${id}`),
        update: (id: string) => url(`/api/pricing/agents/${id}`),
        delete: (id: string) => url(`/api/pricing/agents/${id}`),
        commissions: (id: string) => url(`/api/pricing/agents/${id}/commissions`),
      },
      revenue: {
        summary: url('/api/pricing/revenue'),
        byRegion: url('/api/pricing/revenue/by-region'),
        byPackage: url('/api/pricing/revenue/by-package'),
        export: url('/api/pricing/revenue/export'),
      },
    },
    crm: {
      customers: {
        list: url('/api/crm/customers'),
        create: url('/api/crm/customers'),
        byId: (id: string) => url(`/api/crm/customers/${id}`),
        update: (id: string) => url(`/api/crm/customers/${id}`),
        delete: (id: string) => url(`/api/crm/customers/${id}`),
        bookings: (id: string) => url(`/api/crm/customers/${id}/bookings`),
        communications: (id: string) => url(`/api/crm/customers/${id}/communications`),
        surveys: (id: string) => url(`/api/crm/customers/${id}/surveys`),
        tags: (id: string) => url(`/api/crm/customers/${id}/tags`),
        addTag: (id: string) => url(`/api/crm/customers/${id}/tags`),
        removeTag: (id: string, tagId: string) => url(`/api/crm/customers/${id}/tags/${tagId}`),
      },
      leads: {
        list: url('/api/crm/leads'),
        create: url('/api/crm/leads'),
        byId: (id: string) => url(`/api/crm/leads/${id}`),
        update: (id: string) => url(`/api/crm/leads/${id}`),
        delete: (id: string) => url(`/api/crm/leads/${id}`),
        status: (id: string) => url(`/api/crm/leads/${id}/status`),
        convert: (id: string) => url(`/api/crm/leads/${id}/convert`),
      },
      communications: {
        list: url('/api/crm/communications'),
        create: url('/api/crm/communications'),
        byId: (id: string) => url(`/api/crm/communications/${id}`),
        update: (id: string) => url(`/api/crm/communications/${id}`),
        delete: (id: string) => url(`/api/crm/communications/${id}`),
      },
      surveys: {
        list: url('/api/crm/surveys'),
        create: url('/api/crm/surveys'),
        byId: (id: string) => url(`/api/crm/surveys/${id}`),
        update: (id: string) => url(`/api/crm/surveys/${id}`),
        delete: (id: string) => url(`/api/crm/surveys/${id}`),
      },
      sequences: {
        list: url('/api/crm/sequences'),
        create: url('/api/crm/sequences'),
        byId: (id: string) => url(`/api/crm/sequences/${id}`),
        update: (id: string) => url(`/api/crm/sequences/${id}`),
        delete: (id: string) => url(`/api/crm/sequences/${id}`),
        status: (id: string) => url(`/api/crm/sequences/${id}/status`),
        steps: (id: string) => url(`/api/crm/sequences/${id}/steps`),
        addStep: (id: string) => url(`/api/crm/sequences/${id}/steps`),
        step: (sequenceId: string, stepId: string) => url(`/api/crm/sequences/${sequenceId}/steps/${stepId}`),
      },
    },
    settings: {
      general: {
        get: url('/api/settings/general'),
        update: url('/api/settings/general'),
      },
      users: {
        list: url('/api/settings/users'),
        create: url('/api/settings/users'),
        byId: (id: string) => url(`/api/settings/users/${id}`),
        update: (id: string) => url(`/api/settings/users/${id}`),
        delete: (id: string) => url(`/api/settings/users/${id}`),
        role: (id: string) => url(`/api/settings/users/${id}/role`),
        regions: (id: string) => url(`/api/settings/users/${id}/regions`),
      },
      emailTemplates: {
        list: url('/api/settings/email-templates'),
        create: url('/api/settings/email-templates'),
        byId: (id: string) => url(`/api/settings/email-templates/${id}`),
        update: (id: string) => url(`/api/settings/email-templates/${id}`),
        delete: (id: string) => url(`/api/settings/email-templates/${id}`),
        test: (id: string) => url(`/api/settings/email-templates/${id}/test`),
      },
      notifications: {
        get: url('/api/settings/notifications'),
        update: url('/api/settings/notifications'),
      },
      integrations: {
        list: url('/api/settings/integrations'),
        update: (key: string) => url(`/api/settings/integrations/${encodeURIComponent(key)}`),
        disconnect: (key: string) => url(`/api/settings/integrations/${encodeURIComponent(key)}`),
      },
      auditLogs: {
        list: url('/api/settings/audit-logs'),
        byId: (id: string) => url(`/api/settings/audit-logs/${id}`),
      },
    },
  },
} as const;

export const baseApiUrl = config.baseApiUrl;
export const api = config.api;

export default config;
